<a href="https://colab.research.google.com/github/heddgehogg/KSVD/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B0_1_%D0%A9%D0%B5%D1%80%D0%B1%D0%B8%D0%BD%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота
Щербина Юлія Варіант 1

1. Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.

In [1]:
!pip install numpy

In [2]:
import numpy as np
v = np.arange(1, 21)
print(v)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


2. Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та вивідіть його значення.

In [8]:
m = np.ones((4, 4), dtype=int)
print(m)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


3. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.

In [9]:
m = np.random.uniform(-1, 1, (5, 5))
m

array([[-0.83425989,  0.01553424, -0.07153973, -0.50052417, -0.41928562],
       [-0.15040247,  0.02732449, -0.45930613, -0.58952293,  0.81379279],
       [-0.12026796, -0.0965639 , -0.98121587,  0.56680739,  0.16579341],
       [-0.41555595,  0.85620267, -0.89646047, -0.08698204, -0.47526627],
       [ 0.70799596, -0.39922738, -0.64773199, -0.97973832,  0.17586194]])

4. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [12]:
m = np.random.uniform(0, 1, (3, 3))
m

array([[0.34206583, 0.99528831, 0.94106088],
       [0.80833745, 0.56423394, 0.06373859],
       [0.92138665, 0.25310528, 0.13266711]])

5. Створіть два одновимірних масиви розміром 6, заповніть їх випадкоми дійсними числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

In [19]:
a = np.random.uniform(1, 20, 6)
b = np.random.uniform(1, 20, 6)
print("Вектор а =", a)
print("Вектор b =", b)

Вектор а = [15.71926478 15.52685353 13.58367369 10.51972184 11.71122009 10.22383408]
Вектор b = [ 5.20949693  8.64127542 19.33606975 10.12328658  2.86358679 19.43792384]


In [20]:
print("Сума:", a + b)
print("Різниця:", a - b)
print("Добуток:", a * b)

Сума: [20.92876171 24.16812895 32.91974344 20.64300842 14.57480688 29.66175793]
Різниця: [10.50976786  6.88557812 -5.75239607  0.39643526  8.8476333  -9.21408976]
Добуток: [ 81.88946156 134.17181773 262.65486195 106.49415893  33.53609515
 198.73010829]


6. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.

In [15]:
a = np.random.randint(1, 6, (3, 2))
b = np.random.randint(1, 6, (2, 4))
print("Перша матриця:")
print(a)
print("Друга матриця:")
print(b)

Перша матриця:
[[2 4]
 [2 2]
 [4 5]]
Друга матриця:
[[3 3 5 1]
 [2 5 1 5]]


In [18]:
print("Результат множення матриць:")
print(a.dot(b))

Результат множення матриць:
[[14 26 14 22]
 [10 16 12 12]
 [22 37 25 29]]


7. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [19]:
m = np.random.uniform(0, 1, (3, 3))
print(m)

[[0.91545186 0.23767851 0.01995054]
 [0.48108436 0.5184264  0.5422309 ]
 [0.09977756 0.61552636 0.73369684]]


In [20]:
b = m.T
print("Транспонована матриця:")
print(b)

Транспонована матриця:
[[0.91545186 0.48108436 0.09977756]
 [0.23767851 0.5184264  0.61552636]
 [0.01995054 0.5422309  0.73369684]]


8. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [23]:
a = np.random.randint(1, 10, (3, 3))
b = np.random.randint(1, 10, (3, 3))
print("Перша матриця:")
print(a)
print("Друга матриця:")
print(b)

Перша матриця:
[[3 2 6]
 [6 6 5]
 [5 3 2]]
Друга матриця:
[[4 4 4]
 [1 4 7]
 [2 8 9]]


In [24]:
print("Різниця матриць:")
print(a - b)

Різниця матриць:
[[-1 -2  2]
 [ 5  2 -2]
 [ 3 -5 -7]]


9. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.

In [25]:
a = np.random.randint(-5, 5, (3, 3))
b = np.random.randint(-5, 5, (3, 3))
print("Перша матриця:")
print(a)
print("Друга матриця:")
print(b)

Перша матриця:
[[-2 -3 -4]
 [-2  1  3]
 [-3  1 -5]]
Друга матриця:
[[-2 -5 -5]
 [ 4  0 -5]
 [ 0 -5  2]]


In [27]:
print("Добуток матриць:")
print(a.dot(b))

Добуток матриць:
[[-8 30 17]
 [ 8 -5 11]
 [10 40  0]]


10. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [29]:
m = np.random.uniform(-1, 1, (3, 3))
print(m)

[[-0.33137047 -0.70898151  0.38141131]
 [ 0.0238972  -0.63050069  0.82328296]
 [-0.54694346 -0.8320442   0.594271  ]]


In [30]:
cv = m.sum(axis=1).reshape(-1, 1)
print("Вектор-стовпчик сум:")
print(cv)

Вектор-стовпчик сум:
[[-0.65894068]
 [ 0.21667947]
 [-0.78471665]]
